In [1]:
import numpy as np
import pandas as pd

from counterfactuals.datasets.heloc import HelocDataset

In [7]:
import numpy as np

arr = np.array([[0.01, 0.02, 0.01, 0.01, 0.01, 0.01, 0.01, 0.90, 0.01, 0.01]])

print(arr.T)

[[0.01]
 [0.02]
 [0.01]
 [0.01]
 [0.01]
 [0.01]
 [0.01]
 [0.9 ]
 [0.01]
 [0.01]]


In [3]:
arr = np.random.random((10, 4))

In [7]:
arr[:]

array([[0.76462967, 0.10015878, 0.92309967, 0.76464211],
       [0.53321155, 0.20410965, 0.28066219, 0.59183948],
       [0.64126288, 0.58745972, 0.63918225, 0.92629559],
       [0.4091143 , 0.77608044, 0.04853307, 0.08273212],
       [0.54353453, 0.25001406, 0.08704257, 0.89908074],
       [0.73919606, 0.89586847, 0.98718633, 0.54344364],
       [0.80038551, 0.21162868, 0.20183127, 0.57057678],
       [0.15579448, 0.96448328, 0.52353001, 0.48419328],
       [0.2430583 , 0.98415611, 0.61650701, 0.75886233],
       [0.33648213, 0.37451915, 0.49365622, 0.42469478]])

In [5]:
arr[np.arange(arr.shape[0])]

array([[0.76462967, 0.10015878, 0.92309967, 0.76464211],
       [0.53321155, 0.20410965, 0.28066219, 0.59183948],
       [0.64126288, 0.58745972, 0.63918225, 0.92629559],
       [0.4091143 , 0.77608044, 0.04853307, 0.08273212],
       [0.54353453, 0.25001406, 0.08704257, 0.89908074],
       [0.73919606, 0.89586847, 0.98718633, 0.54344364],
       [0.80038551, 0.21162868, 0.20183127, 0.57057678],
       [0.15579448, 0.96448328, 0.52353001, 0.48419328],
       [0.2430583 , 0.98415611, 0.61650701, 0.75886233],
       [0.33648213, 0.37451915, 0.49365622, 0.42469478]])

In [6]:
default_df = pd.read_csv("../data/heloc.csv")

In [7]:
default_df

RiskPerformance  ExternalRiskEstimate  MSinceOldestTradeOpen  \
0                 Bad                    55                    144   
1                 Bad                    61                     58   
2                 Bad                    67                     66   
3                 Bad                    66                    169   
4                 Bad                    81                    333   
...               ...                   ...                    ...   
10454            Good                    73                    131   
10455             Bad                    65                    147   
10456             Bad                    74                    129   
10457             Bad                    72                    234   
10458             Bad                    66                     28   

       MSinceMostRecentTradeOpen  AverageMInFile  NumSatisfactoryTrades  \
0                              4              84                     20   
1                             15              41                      2   
2                              5              24                      9   
3                              1              73                     28   
4                             27             132                     12   
...                          ...             ...                    ...   
10454                          5              57                     21   
10455                         39              68                     11   
10456                          6              64                     18   
10457                         12             113                     42   
10458                          1              17                      4   

       NumTrades60Ever2DerogPubRec  NumTrades90Ever2DerogPubRec  \
0                                3                            0   
1                                4                            4   
2                                0                            0   
3                                1                            1   
4                                0                            0   
...                            ...                          ...   
10454                            0                            0   
10455                            0                            0   
10456                            1                            1   
10457                            2                            2   
10458                            0                            0   

       PercentTradesNeverDelq  MSinceMostRecentDelq  ...  \
0                          83                     2  ...   
1                         100                    -7  ...   
2                         100                    -7  ...   
3                          93                    76  ...   
4                         100                    -7  ...   
...                       ...                   ...  ...   
10454                      95                    80  ...   
10455                      92                    28  ...   
10456                     100                    -7  ...   
10457                      96                    35  ...   
10458                     100                    -7  ...   

       PercentInstallTrades  MSinceMostRecentInqexcl7days  NumInqLast6M  \
0                        43                             0             0   
1                        67                             0             0   
2                        44                             0             4   
3                        57                             0             5   
4                        25                             0             1   
...                     ...                           ...           ...   
10454                    19                             7             0   
10455                    42                             1             1   
10456                    33                             3      

In [40]:
data_binned, bins = pd.cut(default_df["ExternalRiskEstimate"], bins=10, retbins=True)

In [41]:
data_binned

0        (52.8, 63.1]
1        (52.8, 63.1]
2        (63.1, 73.4]
3        (63.1, 73.4]
4        (73.4, 83.7]
             ...     
10454    (63.1, 73.4]
10455    (63.1, 73.4]
10456    (73.4, 83.7]
10457    (63.1, 73.4]
10458    (63.1, 73.4]
Name: ExternalRiskEstimate, Length: 10459, dtype: category
Categories (10, interval[float64, right]): [(-9.103, 1.3] < (1.3, 11.6] < (11.6, 21.9] < (21.9, 32.2] ... (52.8, 63.1] < (63.1, 73.4] < (73.4, 83.7] < (83.7, 94.0]]

In [42]:
bins

array([-9.103,  1.3  , 11.6  , 21.9  , 32.2  , 42.5  , 52.8  , 63.1  ,
       73.4  , 83.7  , 94.   ])

In [2]:
dataset = HelocDataset(file_path="../data/heloc.csv", method="ares")

/Users/lukasz/Genwro/counterfactuals/counterfactuals/datasets/heloc.py:124: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['RiskPerformance'] = data['RiskPerformance'].replace(['Bad', 'Good'],
/Users/lukasz/Genwro/counterfactuals/counterfactuals/datasets/heloc.py:124: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['RiskPerformance'] = data['RiskPerformance'].replace(['Bad', 'Good'],
/Users/lukasz/Genwro/counterfactuals/counterfactuals/datasets/heloc.py:127: SettingWithCopyWarning: 
A value is trying to be set o

In [29]:
class AReS:
    def __init__(self, dataset) -> None:
        self.categorical_features = []
        self.n_bins = 10
        self.dataset = dataset
        self.features_tree = (
            self.dataset.features_tree
        )

    def bin_continuous_features(self, data):
        """
        Method for binning continuous features. Also computes self.bin_mids and self.bin_mids_tree (dictionary
        and dictionary of dictionaries respectively) which store mid point values for each bin range

        Input: original data
        Outputs: data with continuous features binned (default is 10 equally sized bins)
                 list of all feature values, with binned feature values included
                 list of only binned feature values
        """

        self.data_binned = data.copy()
        data_oh, features, continuous_features = [], [], set()
        self.bins = {}
        self.bin_mids = {}
        self.bin_mids_tree = {}
        self.bin_widths = {}
        for x in data.columns:
            if x.split()[0] in self.categorical_features:
                data_oh.append(pd.DataFrame(data[x]))
                features.append(x)
            else:
                self.data_binned[x], self.bins[x] = pd.cut(
                    self.data_binned[x].apply(lambda x: float(x)),
                    bins=self.n_bins,
                    retbins=True,
                )
                one_hot = pd.get_dummies(self.data_binned[x])
                one_hot.columns = pd.Index(list(one_hot.columns))  # necessary?
                data_oh.append(one_hot)
                cols = self.data_binned[x].cat.categories
                self.bin_mids_tree[x] = {}
                width = cols.length[-1]
                self.bin_widths[x] = width
                for i, col in enumerate(cols):
                    feature_value = x + " = " + str(col)
                    features.append(feature_value)
                    continuous_features.add(feature_value)
                    self.features_tree[x].append(feature_value)
                    mid = (
                        cols.mid[1] - width if i == 0 else col.mid
                    )  # adjust for pd.cut extending the first bin
                    self.bin_mids[feature_value] = mid
                    self.bin_mids_tree[x][feature_value] = mid
        data_oh = pd.concat(data_oh, axis=1)
        data_oh.columns = features
        return data_oh, features, continuous_features

In [31]:
ares = AReS(dataset)

In [34]:
data_oh, _, _ = ares.bin_continuous_features(dataset.X)

In [35]:
data_oh

ExternalRiskEstimate = (32.939, 39.1]  \
0                                      False   
1                                      False   
2                                      False   
3                                      False   
4                                      False   
...                                      ...   
10454                                  False   
10455                                  False   
10456                                  False   
10457                                  False   
10458                                  False   

       ExternalRiskEstimate = (39.1, 45.2]  \
0                                    False   
1                                    False   
2                                    False   
3                                    False   
4                                    False   
...                                    ...   
10454                                False   
10455                                False   
10456                                False   
10457                                False   
10458                                False   

       ExternalRiskEstimate = (45.2, 51.3]  \
0                                    False   
1                                    False   
2                                    False   
3                                    False   
4                                    False   
...                                    ...   
10454                                False   
10455                                False   
10456                                False   
10457                                False   
10458                                False   

       ExternalRiskEstimate = (51.3, 57.4]  \
0                                     True   
1                                    False   
2                                    False   
3                                    False   
4                                    False   
...                                    ...   
10454                                False   
10455                                False   
10456                                False   
10457                                False   
10458                                False   

       ExternalRiskEstimate = (57.4, 63.5]  \
0                                    False   
1                                     True   
2                                    False   
3                                    False   
4                                    False   
...                                    ...   
10454                                False   
10455                                False   
10456                                False   
10457                                False   
10458                                False   

       ExternalRiskEstimate = (63.5, 69.6]  \
0                                    False   
1                                    False   
2                                     True   
3                                     True   
4                                    False   
...                                    ...   
10454                                False   
10455                                 True   
10456                                False   
10457                                False   
10458                                 True   

       ExternalRiskEstimate = (69.6, 75.7]  \
0                                    False   
1                                    False   
2                                    False   
3                                    False   
4                                    False   
...                                    ...   
10454                                 True   
10455                                False   
10456                                 True   
10457                                 True   
10458                                False   

       ExternalRiskEstimate = (75.7, 81.8]  \
0                                    False   
1                   